server:
  port: 8282
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/security



secretKeyPlub: 'MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxl2t0MaQE6lQPTArmZXuGiUK3+kJfaOxYMZlV1L7BQDVVWXSTlCrLK/4msVxStLj0ycsI+iH39vVOJ3S2jGpGMB7sNGEcOgAln8s9mYUECe8XUf3EITDITVKFOmlF3uK6ZilrGzk6RmGfuOD/SFNheSUznGE9Ph5EXmJ6Jq2tIUTf89EJScwOIbVP7jZlvRYpZYKBaSPBW7h4sJN/+A1yg6ytDSgmQlWQHajDhhZ0JiwKtb8CDo1Sw5PN5RHvG4xzk7TSq/ihBpUb95GdE1gs9NVjlINZ13NgnK3pwaTPmUH3jyBmmpMJxZ+++CNabU9Je5soGS4AxA7eQkyjJPoRO5b7OBzOOsbRkyuLMcQgUrzu67CP4BbvSTUXbC3qWeN1Hf52eJ+2XM0V3csX9MOYWpjqfzRmuzsp/flYv02Y+LEVQV5/CnOeigWjLyV1dgK9gKtY5f43qbYf/h5J2ptbSdYg8OK/mX3U9cSaMkmYHTMccOeK7o1TR4dVjywh7PDZMDHGsDKfsXdBwfrxq173ve/auUWpMK/TGZ5iWxwOyVbvC5meSKDEACvRwTeUGSgRWaw6f7afr+0YmX9mQy4JykrsG7Iq2fOXSYwQbAybs00l/OJnIOippsqHlqhDCkrNFPlvGTeHZ94d3RQVCMVkrLUhk2BHYs9xpPpHy+XpGsCAwEAAQ=='